"""Initial migration

Revision ID: 550535ca0f9a
Revises: 
Create Date: 2026-03-29 14:08:32.412452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550535ca0f9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
